apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
resources:
  - ns.yaml
  - gitrepository.yaml
  - flux-kustomization.yaml
  - imagerepository.yaml
  - imagepolicy.yaml
  - imageupdateautomation.yaml
  - secrets/blog-deploy-key.encrypted.yaml
  - secrets/ghcr-pull-secret.encrypted.yaml
patches:
  - path: patches/blog-deployment.yaml
