apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - gitrepository.yaml
  - flux-kustomization.yaml
  - imagerepository.yaml
  - imagepolicy.yaml
  - imageupdateautomation.yaml
  - secrets/blog-deploy-key.encrypted.yaml
