namespace: cloudflared
resources:
  - ns.yaml
  - deployment.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    reloader.stakater.com/auto: "true"
configMapGenerator:
  - name: cloudflared
    files:
      - config.yaml
secretGenerator:
  - name: tunnel-origin-cert
    files:
      - secrets/cert.encrypted.pem
  - name: tunnel-credentials
    files:
      - secrets/228fd238-cb69-4336-82bf-f6e628dcdbda.encrypted.json
